language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: QR84L/a8TfWWuNOnBZzz/oZHyLQs2y/I0HRuZxaMxscgxwBlfP/dYsn45jJYffF5tGhNTmvlhB1OARx57YzIlTClPNvUah7H3IyYtjXRiKqxujZ897SP6arANwGV377UqFayE/YcBKhQvAvLOvR9weOEmg5/+ZzfhsbUmqZrrKQQdpI+1qigz5KR3ldNK6LModJ41+ObduA5GeNq6pGNSqFV4Axj4gBB78COvd5OvO/c3FsfPbY5gvAnTMsiveLwNwU/S8mj618hRc76wEQhcpH2yrGNzAFoBoXal1MehhjNQtE5geqVXOeN2dRMGZtgQ1FDvrQTbiatIwRsaMRFauKSDXdE0ERMWYinqBd/hiWxhRdF7Pea72eTYM4udtH+eDDqbyxkv0vwgvoSnJXa9YU0zIlCItA5fUOvz+LeIYfZLcQYJFbSNXGPJjE7GJjktBs5XZWBXclyau4o2wnKLbalJvdaTVaYTmUQ03tnUUTOjJccpUQg68xTROm2VuOV88stjt7tVR4Z8181bgdAfFp2Ld7I6emsB4k1bz46lEWhQ0SUey0C9VAnr+MPaOKKCbXNBsSAkofnp6YUzAzNTEaD0kk6LgjnAh3XIfXlxCZGjzDNKIfV9ddnlf8T0rVZ4QjQJIsOuFXAFcFklvywSVA9E1foKPbNJRVJnzuVU1s=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: VIu+TCTa1o3rfM5i5UJuWsiaqk5w3pklzk2bWPu7QC5MttTN9BVpeIZnSbymiITKnzL44O8B6Z5AEZtI9fDxv0EyNmFTSsi1vCuNQsDixKKatyK88mTs/6KrQl/nfBS/9gsWfTYN0FwjAjjydB4aYTU/F9ey8v/mpmvZCalS9L9W8WS6Yjvda80yv5JybBHG6QO/ekHH74oEEDQr76kmar8HeXC0GHUVhxr8anbHt/St4L8SMhuCt6nkH/MeS/sUytvzjJyjx3H+9zIkVnX8V2loaz50ThWyFf5kZlG9oAhyWn9sd4Aox/+riI/wVIu6ORFddJLAVJPaUEkjG0a693SUiKHrfSh09GI3u5EAKg9jPM6qFFulflkCe4zFNCxY5ScL4UTt1Q/vhluxU2XPNHcropM85VafBcVfRxEW6QWVsO498y9jUPHCDJeccM0SK9ybmBJQkqph4Jkh5p4bJK/A8koVo8gy6U07yxiUKqtnMm9KfLs63UXMP+0etESd3CClnPGf7FzGx8o7ki4V6AT38XYpr/You/Euda8C1mWWb0pTgWQHMiUNp4HyT+/5aQwVfSoEFSrMmH4X8OKwDLfuBMD7HtU9sfndkF+d9/TfPCPRmX8iGjsgwucZf7v+wwM7DRy/vae/gYDHDCOeR103JaS+Z6USwBJJaly7GUc=
    on_success: change
    on_failure: always
